import { makeStyles, shorthands } from '@fluentui/react-components';

const useStyles = makeStyles({
  root: {
    '--c-primary': '#123f58',
    '--c-secondary': '#f5f5f5',
    '--c-text': 'var(--c-primary)',
    '--c-white': '#fff',
    '--c-black': '#111111',
    '--c-red': '#ff0000',
    '--c-light-gray': '#e3e3e3',
    '--c-base-gray': 'var(--c-secondary)',
    '--c-dark-gray': '#4e5288',
    '--c-accent-high': '#692b61',
    '--c-accent-dark': '#5e3c7d',
    '--c-accent-light': '#f6d5f2',
    '--c-error': '#8a0000',
    '--c-error-background': 'rgb(253, 231, 233)',
    '--c-success': '#26b32b',
    '--font-r-small': '1vw',
    '--font-r-base': '3vw',
    '--font-r-large': '5vw',
    '--font-base': '14px',
    '--font-rel-base': '1.2rem',
    '--font-small': 'small',
    '--font-large': 'large',
    '--font-larger': 'x-large',
    '--border-base': '3px',
    '--border-thin': '1px',
    '--border-thicker': '8px',
    '--radius-small': '5px',
    '--radius-base': '10px',
    '--radius-large': '25px',
    '--radius-none': '0',
    '--width-wide': '90%',
    '--width-base': '80%',
    '--width-narrow': '50%',
    '--d-base': '20px',
    '--d-small': '10px',
    '--d-xsmall': '5px',
    '--d-large': '30px',
    '--d-xlarge': '50px',
    '--shadow': '0 0 10px rgba(0, 0, 0, 0.1)',
    width: '100vw',
    display: 'block',
    padding: 'var(--d-base)',
    color: 'var(--c-text)',
  },
  darkTheme: {
    '--c-primary': '#fdfeff',
    '--c-secondary': '#32343e',
    '--c-text': 'var(--c-primary)',
    '--c-white': 'var(--c-secondary)',
    '--c-black': 'var(--c-primary)',
    '--c-red': '#ff0000',
    '--c-light-gray': '#636d9c',
    '--c-dark-gray': '#e3e3e3',
    '--c-base-gray': 'var(--c-secondary)',
    '--c-accent-high': '#dcdef8',
    '--c-accent-dark': 'var(--c-primary)',
    '--c-accent-light': '#032219',
    '--c-error': '#8a0000',
    '--c-error-background': 'rgb(253, 231, 233)',
    '--c-success': '#26b32b',
  },
  html: {
    scrollBehavior: 'smooth',
  },
  ul: {
    marginBlockStart: 0,
    marginBlockEnd: 0,
  },
  button: {
    color: 'var(--c-text)',
    border: 0,
    background: 'none',
    cursor: 'pointer',
    textDecoration: 'underline',
  },
  overlay: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    width: '100%',
    height: 0,
    background: 'var(--c-black)',
    zIndex: 2,
    opacity: 0.8,
    transition: 'all 0.3s ease-in-out',
    '&.active': {
      '@media (max-width: 1024px)': {
        height: '100%',
      },
    },
  },
  displayNone: {
    display: 'none',
    visibility: 'hidden',
  },
  displayFlexGrow: {
    flexGrow: 1,
  },
  containerCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--d-small)',
  },
  containerRow: {
    flexDirection: 'row',
  },
  chatHeaderThread: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  chatContainer: {
    minWidth: '100%',
    transition: 'width 0.3s ease-in-out',
    maxHeight: '100vh',
  },
  chatContainerWrapper: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gutter: 'var(--d-base)',
    '&.aside-open': {
      '.chat__listItem': {
        maxWidth: 'var(--width-wide)',
      },
      '@media (min-width: 1024px)': {
        gridTemplateColumns: '1fr 1fr',
      },
    },
  },
  aside: {
    width: '100%',
    borderLeft: 'var(--border-thin) solid var(--c-light-gray)',
    '@media (max-width: 1024px)': {
      width: 'var(--width-base)',
      top: 'var(-d-large)',
      left: 'auto',
      zIndex: 3,
      background: 'var(--c-white)',
      display: 'block',
      padding: 'var(--d-base)',
      position: 'absolute',
      borderRadius: 'var(--radius-base)',
    },
  },
  formContainer: {
    marginTop: 'var(--d-large)',
    padding: 'var(--d-small)',
    '&.form__container-sticky': {
      position: 'sticky',
      bottom: 0,
      zIndex: 1,
      borderRadius: 'var(--radius-base)',
      background: 'linear-gradient(0deg, var(--c-base-gray) 0%, var(--c-base-gray) 75%, var(--c-base-gray) 100%)',
      boxShadow: 'var(--shadow)',
      padding: 'var(--d-small) var(--d-small) var(--d-large)',
    },
  },
  formLabel: {
    display: 'block',
    padding: 'var(-d-xsmall) 0',
    fontSize: 'var(--font-small)',
  },
  chatboxButton: {
    background: 'var(--c-white)',
    border: 'none',
    color: 'var(--text-color)',
    fontWeight: 'bold',
    cursor: 'pointer',
    borderRadius: '4px',
    marginLeft: '8px',
    width: 'calc(var(--d-large) + var(--d-xlarge))',
    boxShadow: 'var(--shadow)',
    transition: 'background 0.3s ease-in-out',
    '&:hover, &:focus': {
      background: 'var(--c-secondary)',
    },
    '&:hover svg, &:focus svg': {
      opacity: 0.8,
    },
    '&:disabled': {
      opacity: 0.5,
      cursor: 'not-allowed',
    },
  },
  chatboxInputContainer: {
    display: 'flex',
    border: 'var(--border-thin) solid var(--c-black)',
    background: 'var(--c-white)',
    borderRadius: '4px',
    '&:focus-within': {
      outline: '-webkit-focus-ring-color auto 1px',
    },
  },
  chatboxInput: {
    background: 'transparent',
    color: 'var(--text-color)',
    border: 'none',
    padding: 'var(--d-small)',
    flex: '1 1 auto',
    fontSize: '1rem',
    '&:focus-visible': {
      outline: 'none',
    },
    '&:disabled': {
      opacity: 0.5,
      cursor: 'not-allowed',
    },
  },
  chatboxButtonReset: {
    position: 'absolute',
    right: '115px',
    top: '15px',
    background: 'transparent',
    border: 'none',
    color: 'gray',
    background: 'var(--c-accent-dark)',
    borderRadius: '50%',
    color: 'var(--c-white)',
    fontWeight: 'bold',
    height: '20px',
    width: 'var(--d-base)',
    cursor: 'pointer',
  },
  asideHeader: {
    display: 'flex',
    justifyContent: 'end',
  },
  tabComponentContent: {
    padding: 'var(--d-base) var(--d-base) var(--d-base) 0',
  },
  tabComponentParagraph: {
    fontFamily: 'monospace',
    fontSize: 'var(--font-large)',
    border: 'var(--border-thin) solid var(--c-light-gray)',
    borderRadius: 'var(--radius-large)',
    padding: 'var(--d-base)',
  },
  chatHistoryFooter: {
    display: 'flex',
    flexDirection: 'row',
    gap: '10px',
    justifyContent: 'space-between',
    alignSelf: 'center',
    padding: '20px',
  },
  chatHistoryContainer: {
    display: 'flex',
    flexDirection: 'column',
    borderBottom: '3px solid var(--light-gray)',
    marginBottom: '30px',
  },
});

export default useStyles;
